-- Expand role enum without removing existing values.
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'XOLUM_SUPERADMIN';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'TENANT_ADMIN';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'LOGISTICS_MANAGER';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'CONTROL_TOWER';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'REGIONAL_SUPERVISOR';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'SECURITY_MONITOR';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'CONTRACTING_CUSTOMER';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'FINAL_RECIPIENT';
ALTER TYPE "MembershipRole" ADD VALUE IF NOT EXISTS 'XOLUM_SUPPORT';
