import Link from 'next/link';
import { AppShell } from '@/components/app-shell';

const kpis=[['Rutas activas','48','+5 vs ayer','green'],['Entregas del día','142','78% completadas','blue'],['A tiempo','91%','Meta: 90%','green'],['Excepciones','7','Requieren atención','orange'],['Incidentes','1','En atención','red']] as const;
const exceptions=[['Alerta SafeRoute','Unidad U-32 · Parada prolongada en zona de riesgo','Alto impacto','Sin movimiento 15m','Atender','red'],['Entrega fuera de ventana','R-1048 · Cliente: ABC Distribuidora','Alto impacto','ETA +2h 15m','Reasignar','orange'],['Evidencia incompleta','R-1052 · Cliente: Comercial del Norte','Impacto medio','Faltan 2 archivos','Revisar','yellow'],['Desviación de ruta','R-1039 · Unidad U-18','Impacto medio','Desvío 4.2 km','Ver mapa','yellow'],['Reprogramación solicitada','R-1055 · Cliente: Pharma Corp','Bajo impacto','Nueva ventana','Gestionar','blue']] as const;

export default function Home(){return <AppShell title="Bienvenido, Juan Pablo 👋" subtitle="Aquí está lo importante para tomar mejores decisiones.">
<section className="presentation-kpis">{kpis.map(([label,value,detail,tone])=><Link href={label==='Excepciones'?'/exceptions':label==='Incidentes'?'/security':'/routes'} className={`presentation-kpi tone-${tone}`} key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small>{label==='Entregas del día'&&<i><em style={{width:'78%'}}/></i>}</Link>)}</section>
<section className="presentation-main-grid"><article className="presentation-panel exception-panel"><div className="presentation-panel-head"><h2>Excepciones prioritarias <b>7</b></h2><Link href="/exceptions">Ver todas →</Link></div><div className="exception-list">{exceptions.map(([title,meta,impact,detail,action,tone])=><div className={`exception-card border-${tone}`} key={title}><div className={`exception-symbol tone-${tone}`}>!</div><div className="exception-copy"><strong>{title}</strong><span>{meta}</span></div><div className={`exception-impact tone-text-${tone}`}><strong>{impact}</strong><span>{detail}</span></div><Link href={title.includes('SafeRoute')?'/security':'/exceptions'}>{action}</Link></div>)}</div></article>
<article className="presentation-panel map-panel"><div className="presentation-panel-head"><h2>Operación en tiempo real</h2></div><div className="live-map"><div className="road road-a"/><div className="road road-b"/><div className="road road-c"/><div className="route-line route-green"/><div className="route-line route-orange"/><div className="route-line route-blue"/><span className="truck t1">▣</span><span className="truck t2">▣</span><span className="truck t3">▣</span><span className="truck t4">▣</span><span className="incident-pin">◈</span><div className="map-controls"><button>+</button><button>−</button><button>◎</button></div><div className="map-legend"><span className="green">● En ruta <b>39</b></span><span className="orange">● Riesgo <b>5</b></span><span className="red">◈ Incidente <b>1</b></span><span>○ Sin señal <b>3</b></span></div></div></article></section>
<section className="value-principles"><article><b>▣</b><div><strong>Automatizamos<br/>lo repetitivo</strong><span>Menos clics, menos errores,<br/>más tiempo para lo importante.</span></div></article><article><b>⌘</b><div><strong>Conectamos<br/>lo que está separado</strong><span>Datos, personas y sistemas<br/>trabajando juntos.</span></div></article><article><b>✦</b><div><strong>Simplificamos<br/>lo complicado</strong><span>Interfaces claras para<br/>decisiones claras.</span></div></article><article><b>◎</b><div><strong>Con propósito</strong><span>Cada función existe para<br/>resolver un problema real.</span></div></article></section>
</AppShell>}
