import { AppShell } from '@/components/app-shell';
import { KpiCard } from '@/components/kpi-card';
import { StatusPill } from '@/components/status-pill';

const trips=[
['MX-0248','CEDIS Norte → Liverpool Perisur','Sprinter 214 · J. Cruz','12 / 14','16:42','EN RUTA','good'],
['MX-0249','Vallejo → Santa Fe','NP300 088 · M. Ruiz','7 / 11','17:08','RIESGO','warn'],
['MX-0250','Tlalnepantla → Querétaro','Rabón 031 · A. Vega','3 / 8','18:15','INCIDENCIA','bad'],
['MX-0251','Iztapalapa → Toluca','Transit 117 · D. Soto','9 / 9','15:56','COMPLETA','info'],
] as const;

export default function Home(){return <AppShell title="Torre de control" subtitle="Toda la última milla, fiscal y documental en una sola operación.">
<section className="kpi-grid"><KpiCard label="Viajes activos" value="24" delta="+4 hoy"/><KpiCard label="OTIF" value="97.8%" delta="+1.2%" tone="good"/><KpiCard label="Entregas en riesgo" value="3" delta="-2 vs ayer" tone="warn"/><KpiCard label="Revenue at Risk" value="$184,230" delta="7 embarques" tone="bad"/></section>
<section className="control-grid">
<article className="panel map-panel"><div className="panel-head"><div><span className="section-kicker">TIEMPO REAL</span><h2>Operación viva</h2></div><div className="legend"><span><i className="dot good"/>A tiempo</span><span><i className="dot warn"/>Riesgo</span><span><i className="dot bad"/>Incidencia</span></div></div><div className="map-canvas"><div className="road r1"/><div className="road r2"/><div className="road r3"/><div className="zone z1"/><div className="zone z2"/><div className="pin p1 good">12</div><div className="pin p2 warn">7</div><div className="pin p3 bad">3</div><div className="pin p4 good">9</div><div className="map-overlay"><strong>CDMX · Zona Centro</strong><span>24 unidades monitoreadas</span></div></div></article>
<article className="panel alerts"><div className="panel-head"><div><span className="section-kicker">IA OPERATIVA</span><h2>Atención requerida</h2></div><StatusPill tone="bad">3 críticas</StatusPill></div><div className="alert-item"><div className="alert-icon">!</div><div><strong>Ruta MX-0250 fuera de SLA</strong><p>6 entregas podrían salir de ventana. Reasignar 3 paradas aumenta OTIF a 98.6%.</p><button className="text-action">Revisar recomendación →</button></div></div><div className="alert-item"><div className="alert-icon warn">⌁</div><div><strong>Desviación anormal detectada</strong><p>Unidad NP300 088 lleva 18 min fuera del corredor planificado.</p></div></div><div className="alert-item"><div className="alert-icon info">◇</div><div><strong>2 CFDI por validar</strong><p>Viajes listos físicamente, pendientes de validación fiscal previa a liberación.</p></div></div></article>
</section>
<section className="panel table-panel"><div className="panel-head"><div><span className="section-kicker">EJECUCIÓN</span><h2>Viajes de hoy</h2></div><button className="ghost">Ver todos</button></div><div className="table-wrap"><table><thead><tr><th>Viaje</th><th>Ruta</th><th>Unidad / Operador</th><th>Entregas</th><th>ETA cierre</th><th>Estado</th></tr></thead><tbody>{trips.map(t=><tr key={t[0]}><td><strong>{t[0]}</strong></td><td>{t[1]}</td><td>{t[2]}</td><td>{t[3]}</td><td>{t[4]}</td><td><StatusPill tone={t[6] as 'good'|'warn'|'bad'|'info'}>{t[5]}</StatusPill></td></tr>)}</tbody></table></div></section>
<section className="bottom-grid"><article className="panel"><div className="panel-head"><div><span className="section-kicker">DOCUMENTACIÓN</span><h2>Salud documental</h2></div><strong className="score">94%</strong></div><div className="progress-list"><div><span>POD completos <b>91%</b></span><i><em style={{width:'91%'}}/></i></div><div><span>Materialidad <b>88%</b></span><i><em style={{width:'88%'}}/></i></div><div><span>Fiscal MX <b>97%</b></span><i><em style={{width:'97%'}}/></i></div></div></article><article className="panel"><div className="panel-head"><div><span className="section-kicker">DINERO</span><h2>Bloqueos de facturación</h2></div></div><div className="money-row"><span>POD incompleto</span><strong>$92,480</strong></div><div className="money-row"><span>Recepción pendiente</span><strong>$58,300</strong></div><div className="money-row"><span>Validación fiscal</span><strong>$33,450</strong></div></article></section>
</AppShell>}
